/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.42.0.0
 *
 * Project: 'Projet_V3' 
 * Target:  'Target 1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f2xx.h"

/* Keil::CMSIS Driver:USART@2.12 */
#define RTE_Drivers_USART1              /* Driver USART1 */
#define RTE_Drivers_USART2              /* Driver USART2 */
#define RTE_Drivers_USART3              /* Driver USART3 */
#define RTE_Drivers_USART4              /* Driver USART4 */
#define RTE_Drivers_USART5              /* Driver USART5 */
#define RTE_Drivers_USART6              /* Driver USART6 */
/* Keil::Device:STM32Cube Framework:Classic@1.2.8 */
#define RTE_DEVICE_FRAMEWORK_CLASSIC
/* Keil::Device:STM32Cube HAL:ADC@1.2.8 */
#define RTE_DEVICE_HAL_ADC
/* Keil::Device:STM32Cube HAL:Common@1.2.8 */
#define RTE_DEVICE_HAL_COMMON
/* Keil::Device:STM32Cube HAL:Cortex@1.2.8 */
#define RTE_DEVICE_HAL_CORTEX
/* Keil::Device:STM32Cube HAL:DAC@1.2.8 */
#define RTE_DEVICE_HAL_DAC
/* Keil::Device:STM32Cube HAL:DMA@1.2.8 */
#define RTE_DEVICE_HAL_DMA
/* Keil::Device:STM32Cube HAL:GPIO@1.2.8 */
#define RTE_DEVICE_HAL_GPIO
/* Keil::Device:STM32Cube HAL:RCC@1.2.8 */
#define RTE_DEVICE_HAL_RCC
/* Keil::Device:STM32Cube HAL:RTC@1.2.8 */
#define RTE_DEVICE_HAL_RTC
/* Keil::Device:STM32Cube HAL:TIM@1.2.8 */
#define RTE_DEVICE_HAL_TIM
/* Keil::Device:STM32Cube HAL:USART@1.2.8 */
#define RTE_DEVICE_HAL_USART
/* Keil::Device:Startup@2.2.2 */
#define RTE_DEVICE_STARTUP_STM32F2XX    /* Device Startup for STM32F2 */


#endif /* RTE_COMPONENTS_H */
